# Generated by Django 5.1.1 on 2024-12-14 10:50
from django.utils import timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_word_column_article_word_count'),
    ]

    def create_superuser(apps, schema_editor):

        User = apps.get_model('app', 'UserProfile')
        
        if User.objects.filter(email='admin@example.com').exists():
            return
        
        superuser = User.objects.create_superuser(
            email='admin@example.com',
            password='1234',
            last_login=timezone.now()
        )
        superuser.save()

    operations = [
        migrations.RunPython(create_superuser),
    ]
