# Generated by Django 5.1.4 on 2024-12-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
