# Generated by Django 5.1.4 on 2024-12-16 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_userprofile_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
    ]
